export const LOAD_RECENT_POSTS = 'wp-react-post-edit/LOAD_RECENT_POSTS'
export const LOAD_RECENT_POSTS_SUCCESS = 'wp-react-post-edit/LOAD_RECENT_POSTS_SUCCESS'
export const LOAD_RECENT_POSTS_ERROR = 'wp-react-post-edit/LOAD_RECENT_POSTS_ERROR'
export const DELETE_POST = 'wp-react-post-edit/DELETE_POST'
export const DELETE_POST_SUCCESS = 'wp-react-post-edit/DELETE_POST_SUCCESS'
export const DELETE_POST_ERROR = 'wp-react-post-edit/DELETE_POST_ERROR'
